apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: saikumar
    spec:
      containers:
      - name: saikumargollu
        image: nginx
        ports:
        - containerPort: 80

